nextyio/gonex

- internal/ethapi/api.go
> ethapi: default to use eip-155 protected transactions

- trie/database.go
> trie/database: add a missing unlock

- p2p/protocols/protocol.go
- p2p/protocols/reporter.go
>  p2p/protocols: some fixes on p2p protocol

- cmd/puppeth/wizard_genesis.go
- consensus/dccs/dccs.go
- eth/backend.go
- params/config.go
> Consensus address field name and address

- core/state/statedb.go
- core/state/statedb_test.go
Co-authored-by: atsushi-ishibashi <a.ishibashi0501@gmail.com>
> core/state: memory efficient, add AddPreimage test

- cmd/puppeth/wizard_genesis.go
- consensus/dccs/dccs.go
- core/vm/evm.go
- params/config.go
> Consensus level Contract Deployment

- consensus/dccs/dccs.go
> consensus/dccs: nil check the ThangLong config param on initialization

- rlp/decode.go
Prevents reallocation, improves performance
https://github.com/ethereum/go-ethereum/pull/19044
> rlp: added pooling of streams using sync

- cmd/puppeth/wizard_genesis.go
- consensus/dccs/dccs.go
> Correct the NTF manager to hardcoded address

- cmd/puppeth/module_explorer.go
- cmd/puppeth/wizard_explorer.go
- cmd/puppeth/wizard_network.go
Co-authored-by: rjl493456442 <garyrong0905@gmail.com>
> cmd/puppeth: integrate blockscout

- params/config.go
> params: enable ThangLong hardfork on mainnet

- cmd/geth/main.go
> cmd/geth: revert the client identifier to geth

- consensus/dccs/dccs.go
- core/blockchain.go
- params/config.go
> Non-archive mode sealing

- README.md
> Gonex edit

- .gitignore
- cmd/gonex/config.go
- cmd/gonex/consolecmd.go
- cmd/gonex/monitorcmd.go
- console/console.go
- eth/backend.go
- node/config.go
- node/defaults.go
> rename all ethereum/geth into nexty/gonex

- cmd/puppeth/module_ethstats.go
> cmd/puppeth: integrate new nexty stats into puppeth

- params/config.go
> update trusted checkpoint for nexty mainnet

- vendor/github.com/syndtr/goleveldb/leveldb/db.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_snapshot.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_transaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/session.go
- vendor/github.com/syndtr/goleveldb/leveldb/session_compaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/session_util.go
- vendor/github.com/syndtr/goleveldb/leveldb/table.go
- vendor/github.com/syndtr/goleveldb/leveldb/version.go
- vendor/vendor.json
leveldb have some updates to improve performance and lower disk writing pressure, hope this can fix #230 when running on node with 4 GB RAM
> vendor: udpate leveldb upstream

- consensus/dccs/dccs.go
backport the fix #245 into branch `2.0`
> dccs: cast vote if the block is not a checkpoint

- Dockerfile
- Dockerfile.alltools
We need gonex docker image in some other places
> Modify Dockerfile for gonex

- internal/web3ext/web3ext.go
backport #252 to master branch
> internal: add web3 extension for dccs

- accounts/abi/bind/backends/real.go
- core/evm.go
- core/state_transition.go
- params/config.go
For interaction between consensus and state via contract.
> Implement real backend

- core/vdf/engine.go
- core/vm/common.go
- core/vm/contracts.go
- core/vm/evm.go
- eth/tracers/tracer.go
- params/protocol_params.go
- vendor/github.com/harmony-one/vdf/.gitignore
- vendor/github.com/harmony-one/vdf/LICENSE
- vendor/github.com/harmony-one/vdf/README.md
- vendor/github.com/harmony-one/vdf/go.mod
- vendor/github.com/harmony-one/vdf/go.sum
- vendor/github.com/harmony-one/vdf/src/vdf_go/classgroup.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/discriminant.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/division.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/encode.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/gcd.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/prime.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/proof_wesolowski.go
- vendor/github.com/harmony-one/vdf/src/vdf_go/vdf.go
core/vm, params: precompiled contract for vdf verification
> VDF engine for both cli and golib support

- cmd/gonex/config.go
- cmd/gonex/main.go
- cmd/gonex/usage.go
- cmd/utils/flags.go
- eth/backend.go
- eth/config.go
For debug and development only
> eth,cmd: implement rollback param

- core/blockchain.go
- eth/downloader/downloader.go
Including:
* https://github.com/ethereum/go-ethereum/issues/18388
* https://github.com/ethereum/go-ethereum/issues/18994
> Fix some unsolved of geth

- consensus/dccs/1_dccs.go
- consensus/dccs/1_snapshot.go
- consensus/dccs/api.go
- consensus/dccs/dccs.go
- consensus/dccs/snapshot.go
- core/blockchain.go
Lighting fast syncing and node performance.
> Stateless header chain verification

- core/vdf/delayer.go
- core/vdf/delayer_test.go
- core/vdf/engine.go
- core/vdf/engine_test.go
- vendor/github.com/fortytw2/leaktest/.travis.yml
- vendor/github.com/fortytw2/leaktest/LICENSE
- vendor/github.com/fortytw2/leaktest/README.md
- vendor/github.com/fortytw2/leaktest/leaktest.go
- vendor/github.com/fortytw2/leaktest/leaktest_test.go
- vendor/github.com/fortytw2/leaktest/leaktest_utils_test.go
Unit tests.
CLI interrupt signal handling.
Broadcasting and canceling.
Caching.
Non-blocking stop channel for vdf_go implementation.
> VDF and delayer improvement

- cmd/puppeth/wizard_genesis.go
- consensus/dccs/1_dccs.go
- consensus/dccs/2_dccs.go
- consensus/dccs/2_ext.go
- consensus/dccs/2_logfilter.go
- consensus/dccs/2_queue.go
- consensus/dccs/2_queue_test.go
- consensus/dccs/dccs.go
- core/types/block.go
- eth/filters/filter.go
- params/config.go
To solve #238, #239, #258 and #136
Features:
* Fully secure fastsync and header chain verification. (No state required)
* Relay/light client support with cross-linking and anchoring. No trusted checkpoint, contract nor dev keys.
* No epoch (what so ever).
* Sealer inactivity leakage: after 1024 block of inactivity, sealer will be excluded from the active list. No slashing yet.
* Sealer join and leave applications will be directly recorded to the header. The application will be active after 128 confirmations.
* Sealer list is shuffled using unbiasable VDF output.
* Smooth recent list condition: n/2 recent rule is preserved even at the VDF seed key block (which the order of the list start to change).
> Consensus for CoLoa hardfork

- cmd/puppeth/wizard_genesis.go
- consensus/dccs/2_dccs.go
- params/config.go
> protocol level config for RandomSeedIteration

- cmd/gonex/config.go
- cmd/gonex/main.go
- cmd/gonex/usage.go
- cmd/utils/flags.go
- consensus/dccs/2_dccs.go
- consensus/dccs/2_price.go
- consensus/dccs/dccs.go
- eth/backend.go
- eth/config.go
- les/client.go
> configurable price service URL

- core/state_transition.go
- core/vm/evm.go
- core/vm/instructions.go
- params/log_params.go
> use tx value as the value limit for tx code to spend

- consensus/dccs/2_dccs.go
- consensus/dccs/2_price.go
- eth/config.go
> don't init the price engine when price.url not configured

- consensus/dccs/2_queue.go
> Finalize majority continuity ratio and recent list size
